# Parellization
suppressMessages({
  library(future)
})

options(future.globals.maxSize = 3 * 1024^3)  # Increase limit to 3 GB
plan(multisession, workers = 15)  # Use 5 cores (adjust as needed)

# Load libraries and Set Seed
suppressMessages({
  .libPaths("~/R/x86_64-pc-linux-gnu-library/4.2/")
  library(tidyverse)
  library(BiocManager)
  library(rlang)
  library(dbplyr)
  library(celldex)
  library(SingleR)
  library(progeny)
  library(MAST)
  library(gghalves)
  library(destiny)
  library(ggalluvial)
  library(ggbeeswarm)
  library(ggthemes)
  library(magrittr)
  library(RColorBrewer)
  library(dplyr)
  library(corrplot)
  library(pheatmap)
  library(ComplexHeatmap)
  library(scales)
  library(viridis)
  library(circlize)
  library(ggrepel)
  library(Seurat)
  library(SeuratData)
  library(clustree)
  library(gridExtra)
  library(rstatix)
  library(patchwork)
  library(ggplot2)
  library(data.table)
  library(ggpubr)
  library(SCpubr)
  library(SeuratWrappers)
  library(harmony)
  library(splatter)
  library(msigdbr)
  library(GEOquery)
  library(scater)
  library(SingleCellExperiment)
  library(viridisLite)
  library(stringr)
  library(colorRamps)
  library(devtools)
  # library(SeuratObject)
  library(Nebulosa)
  library(parallel)
  library(future)
  library(future.apply)
  library(clusterProfiler)
  library(org.Hs.eg.db) # Replace with appropriate organism if not human
  library(AUCell)
  library(ggradar)
  library(readxl)
  library(scCustomize)
  library(random)
  set.seed(1052)
})

# Setting directories and loading main dataset
wd <- dirname(getwd())
data_folder <- file.path("data/")
output_folder <- file.path("output/")
figures_folder <- file.path("figures")

load("data/21DING021-FinalEmbedding.RData")
